[package]
name = "flt-regular"
version = "0.1"
lean_version = "leanprover-community/lean:3.49.1"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "cce7f68a7eaadadf74c82bbac20721cdc03a1cc1"}
