[package]
name = "flt-regular"
version = "0.1"
lean_version = "leanprover-community/lean:3.49.0"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "fd47bdf09e90f553519c712378e651975fe8c829"}
