[package]
name = "flt-regular"
version = "0.1"
lean_version = "leanprover-community/lean:3.35.1"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "75207e917a636b2138556a2c978dded8f2ec2b05"}
