module

public import Mathlib.NumberTheory.Cyclotomic.Basic
import Mathlib.NumberTheory.NumberField.Cyclotomic.Ideal

/-!
# Ideals in rational cyclotomic fields

This file develops coprimality criteria for ideals generated by `x + yη` and a coefficient
divisibility result for integral linear combinations of roots of unity.
-/

@[expose] public section

open FiniteDimensional Polynomial Algebra Nat Finset Fintype

variable (p : ℕ) (L : Type*) [Field L] [CharZero L] [IsCyclotomicExtension {p} ℚ L]

section IntFacts

open scoped NumberField

open Ideal IsCyclotomicExtension

local notation "R" => 𝓞 (CyclotomicField p ℚ)

/-- The principal ideal generated by `x + y ζ^i` for integer `x` and `y` -/
@[nolint unusedArguments]
noncomputable
def fltIdeals [Fact p.Prime] (x y : ℤ) {η : R} (_ : η ∈ nthRootsFinset p 1) : Ideal R :=
  Ideal.span ({x + η * y} : Set R)

variable {p}

theorem mem_fltIdeals [Fact p.Prime] (x y : ℤ) {η : R} (hη : η ∈ nthRootsFinset p 1) :
    ↑x + η * ↑y ∈ fltIdeals p x y hη :=
  mem_span_singleton.mpr dvd_rfl

open IsPrimitiveRoot

theorem aux_lem_flt [Fact p.Prime] {x y z : ℤ} (H : x ^ p + y ^ p = z ^ p)
    (caseI : ¬↑p ∣ x * y * z) : ¬(p : ℤ) ∣ (x + y : ℤ) := by
  intro habs
  replace habs : ↑p ∣ (x + y : ℤ) := by simpa using habs
  rw [← ZMod.intCast_zmod_eq_zero_iff_dvd, Int.cast_add] at habs
  replace H := congr_arg (fun x : ℤ ↦ (x : ZMod p)) H.symm
  simp only [Int.cast_add, Int.cast_pow, ZMod.pow_card, habs,
    ZMod.intCast_zmod_eq_zero_iff_dvd] at H
  exact caseI (Dvd.dvd.mul_left H _)

theorem diff_of_roots [hp : Fact p.Prime] (ph : 5 ≤ p) {η₁ η₂ : R}
    (hη₁ : η₁ ∈ nthRootsFinset p 1) (hη₂ : η₂ ∈ nthRootsFinset p 1)
    (hdiff : η₁ ≠ η₂) (hwlog : η₁ ≠ 1) :
    ∃ u : Rˣ, η₁ - η₂ = u * (1 - η₁) := by
  have _ : 2 ≤ p := le_trans (by decide) ph
  have h := isPrimitiveRoot_of_mem_nthRootsFinset Fact.out hη₁ hwlog
  rcases h.nthRootsFinset_pairwise_associated_sub_one_sub_of_prime hp.out hη₁ hη₂ hdiff with
    ⟨u, hu⟩
  refine ⟨-u, by grind [Units.val_neg]⟩

theorem diff_of_roots2 [Fact p.Prime] (ph : 5 ≤ p) {η₁ η₂ : R}
    (hη₁ : η₁ ∈ nthRootsFinset p 1) (hη₂ : η₂ ∈ nthRootsFinset p 1)
    (hdiff : η₁ ≠ η₂) (hwlog : η₁ ≠ 1) :
    ∃ u : Rˣ, η₂ - η₁ = u * (1 - η₁) := by
  obtain ⟨u, hu⟩ := diff_of_roots ph hη₁ hη₂ hdiff hwlog
  exact ⟨-u, by simp [← hu]⟩

lemma fltIdeals_coprime2_lemma [Fact p.Prime] (ph : 5 ≤ p) {x y : ℤ} {η₁ η₂ : R}
    (hη₁ : η₁ ∈ nthRootsFinset p 1)
    (hη₂ : η₂ ∈ nthRootsFinset p 1) (hdiff : η₁ ≠ η₂) (hp : IsCoprime x y)
    (hp2 : ¬(p : ℤ) ∣ (x + y : ℤ)) (hwlog : η₁ ≠ 1) :
    (fltIdeals p x y hη₁) ⊔ (fltIdeals p x y hη₂) = ⊤ := by
  rw [fltIdeals, fltIdeals, Ideal.sup_eq_top_iff_isCoprime]
  have hdvd : (1 - η₁ : R) ∣ p := by
    rw [← neg_sub, neg_dvd]
    exact sub_one_dvd_natCast_of_pow_eq_one
      ((mem_nthRootsFinset (NeZero.pos p) 1).mp hη₁) hwlog
  have hcop : IsCoprime (1 - η₁ : R) (x + y : R) := by
    simpa only [map_add, eq_intCast] using
      (((Nat.prime_iff_prime_int.mp Fact.out).coprime_iff_not_dvd.mpr hp2).map
        (algebraMap ℤ R)).of_isCoprime_of_dvd_left hdvd
  have hroot : IsCoprime (x + η₁ * y : R) (1 - η₁) := by
    convert hcop.symm.add_mul_left_left (-y) using 1
    ring
  obtain ⟨u, hu⟩ := diff_of_roots ph hη₁ hη₂ hdiff hwlog
  have hdiff : IsCoprime (x + η₁ * y : R) ((η₁ - η₂) * y) := by
    rw [hu, mul_assoc, isCoprime_mul_unit_left_right u.isUnit]
    exact hroot.mul_right (hp.intCast.add_mul_right_left η₁)
  convert hdiff.neg_right.add_mul_right_right 1 using 1
  ring

theorem fltIdeals_coprime2 [Fact p.Prime] (ph : 5 ≤ p) {x y : ℤ} {η₁ η₂ : R}
    (hη₁ : η₁ ∈ nthRootsFinset p 1) (hη₂ : η₂ ∈ nthRootsFinset p 1)
    (hdiff : η₁ ≠ η₂) (hp : IsCoprime x y)
    (hp2 : ¬(p : ℤ) ∣ (x + y : ℤ)) (hwlog : η₁ ≠ 1) :
    IsCoprime (fltIdeals p x y hη₁) (fltIdeals p x y hη₂) := by
  simpa [Ideal.isCoprime_iff_add] using
    fltIdeals_coprime2_lemma ph hη₁ hη₂ hdiff hp hp2 hwlog

theorem fltIdeals_coprime (hpri : p.Prime) (p5 : 5 ≤ p) {x y z : ℤ}
    (H : x ^ p + y ^ p = z ^ p) {η₁ η₂ : R} (hxy : IsCoprime x y)
    (hη₁ : η₁ ∈ nthRootsFinset p 1) (hη₂ : η₂ ∈ nthRootsFinset p 1)
    (hdiff : η₁ ≠ η₂)
    (caseI : ¬↑p ∣ x * y * z) :
    have : Fact p.Prime := ⟨hpri⟩
    IsCoprime (fltIdeals p x y hη₁) (fltIdeals p x y hη₂) := by
  have : Fact p.Prime := ⟨hpri⟩
  by_cases h : η₁ ≠ 1
  · exact fltIdeals_coprime2 p5 hη₁ hη₂ hdiff hxy (aux_lem_flt H caseI) h
  · have h2 : η₂ ≠ 1 := by
      simp only [ne_eq, not_not] at h
      rw [h] at hdiff
      exact hdiff.symm
    exact (fltIdeals_coprime2 p5 hη₂ hη₁ hdiff.symm hxy (aux_lem_flt H caseI) h2).symm

variable {L}

theorem dvd_coeff_cycl_integer (hp : p.Prime) {ζ : 𝓞 L} (hζ : IsPrimitiveRoot ζ p)
    {f : Fin p → ℤ} (hf : ∃ i, f i = 0) {m : ℤ}
    (hdiv : ↑m ∣ ∑ j, f j • ζ ^ (j : ℕ)) : ∀ j, m ∣ f j := by
  have : Fact p.Prime := ⟨hp⟩
  obtain ⟨n, rfl⟩ : ∃ n, p = n + 1 := ⟨p.pred, (succ_pred_prime hp).symm⟩
  have hζ' : IsPrimitiveRoot (ζ : L) (n + 1) := IsPrimitiveRoot.coe_submonoidClass_iff.2 hζ
  set b := hζ'.integralPowerBasis with hb
  have hdim : b.dim = n := by rw [hb, hζ'.integralPowerBasis_dim, totient_prime hp,
    Nat.add_sub_cancel]
  have hbasis (i : Fin b.dim) : b.basis i = ζ ^ (i : ℕ) := by
    rw [PowerBasis.basis_eq_pow, show b.gen = hζ'.toInteger from hζ'.integralPowerBasis_gen]
    rfl
  have hgeom : ∑ i : Fin n, ζ ^ (i : ℕ) = -ζ ^ n := by
    rw [Fin.sum_univ_eq_sum_range (fun i ↦ ζ ^ i) n]
    exact eq_neg_of_add_eq_zero_left
      (by simpa [sum_range_succ] using hζ.geom_sum_eq_zero hp.one_lt)
  -- Since `ζ ^ n = -(1 + ζ + ⋯ + ζ ^ (n - 1))`, the sum `∑ j, f j • ζ ^ j` has
  -- coordinates `f j - f (Fin.last n)` in the integral power basis `1, ζ, …, ζ ^ (n - 1)`.
  have hsum : (∑ j, f j • ζ ^ (j : ℕ)) = b.basis.equivFun.symm
      fun i ↦ f ⟨i, (i.2.trans_le hdim.le).trans n.lt_succ_self⟩ - f (Fin.last n) := by
    rw [Module.Basis.equivFun_symm_apply, Fintype.sum_equiv (finCongr hdim)
      (fun i : Fin b.dim ↦
        (f ⟨i, (i.2.trans_le hdim.le).trans n.lt_succ_self⟩ - f (Fin.last n)) • b.basis i)
      (fun i : Fin n ↦ (f ⟨i, i.2.trans n.lt_succ_self⟩ - f (Fin.last n)) • ζ ^ (i : ℕ))
      fun i ↦ by
        rw [hbasis]
        rfl]
    simp only [sub_smul, sum_sub_distrib, ← Finset.smul_sum, hgeom, smul_neg, sub_neg_eq_add]
    exact Fin.sum_univ_castSucc fun j : Fin (n + 1) ↦ f j • ζ ^ (j : ℕ)
  obtain ⟨y, hy⟩ := hdiv
  rw [hsum, ← zsmul_eq_mul] at hy
  have key (i : Fin b.dim) :
      m ∣ f ⟨i, (i.2.trans_le hdim.le).trans n.lt_succ_self⟩ - f (Fin.last n) := by
    have h1 : f ⟨i, (i.2.trans_le hdim.le).trans n.lt_succ_self⟩ - f (Fin.last n) =
        b.basis.coord i (m • y) := by rw [← hy, b.basis.coord_equivFun_symm]
    rw [h1]
    exact b.basis.dvd_coord_smul i y m
  have hlast : m ∣ f (Fin.last n) := by
    obtain ⟨i, hi⟩ := hf
    rcases (Nat.lt_succ_iff.mp i.2).eq_or_lt with h | h
    · rw [← show i = Fin.last n from Fin.ext h, hi]
      exact dvd_zero m
    · simpa [hi] using key ⟨i, hdim.symm ▸ h⟩
  intro j
  rcases (Nat.lt_succ_iff.mp j.2).eq_or_lt with h | h
  · exact (show j = Fin.last n from Fin.ext h) ▸ hlast
  · simpa using (key ⟨j, hdim.symm ▸ h⟩).add hlast

end IntFacts
