import Mathlib.RingTheory.Polynomial.Eisenstein.IsIntegral
import FltRegular.NumberTheory.Cyclotomic.GaloisActionOnCyclo
import Mathlib.NumberTheory.Cyclotomic.Rat
import FltRegular.NumberTheory.Cyclotomic.UnitLemmas
import Mathlib.RingTheory.DedekindDomain.Ideal
import FltRegular.NumberTheory.Cyclotomic.ZetaSubOnePrime
import FltRegular.NumberTheory.Cyclotomic.CyclotomicUnits
import Mathlib.Algebra.CharP.Quotient

universe u

open FiniteDimensional Polynomial Algebra Nat Finset Fintype

variable (p : ℕ+) (L : Type u) [Field L] [CharZero L] [IsCyclotomicExtension {p} ℚ L]

instance Ring.toSubtractionMonoid {S : Type*} [Ring S] : SubtractionMonoid S := inferInstance

section IntFacts

noncomputable section

open scoped NumberField BigOperators

open Ideal IsCyclotomicExtension

-- TODO can we make a relative version of this with another base ring instead of ℤ ?
-- A version of flt_facts_3 indep of the ring
theorem exists_int_sub_pow_prime_dvd {A : Type _} [CommRing A] [IsCyclotomicExtension {p} ℤ A]
    [hp : Fact (p : ℕ).Prime] (a : A) : ∃ m : ℤ, a ^ (p : ℕ) - m ∈ span ({(p : A)} : Set A) := by
  have : a ∈ Algebra.adjoin ℤ _ := @adjoin_roots {p} ℤ A _ _ _ _ a
  refine' Algebra.adjoin_induction this _ _ _ _
  · intro x hx
    rcases hx with ⟨hx_w, hx_m, hx_p⟩
    simp only [Set.mem_singleton_iff] at hx_m
    rw [hx_m] at hx_p
    simp only [hx_p]
    use 1
    simp
  · intro r
    use r ^ (p : ℕ)
    simp
  · rintro x y ⟨b, hb⟩ ⟨c, hc⟩
    obtain ⟨r, hr⟩ := exists_add_pow_prime_eq hp.out x y
    rw [hr]
    use c + b
    push_cast
    rw [sub_add_eq_sub_sub, sub_eq_add_neg, sub_eq_add_neg, add_comm _ (↑↑p * r), add_assoc,
      add_assoc]
    apply Ideal.add_mem _ _
    · convert Ideal.add_mem _ hb hc using 1
      ring
    · rw [mem_span_singleton]
      exact dvd_mul_right _ _
  · rintro x y ⟨b, hb⟩ ⟨c, hc⟩
    rw [mul_pow]
    use b * c
    have := Ideal.mul_mem_left _ (x ^ (p : ℕ)) hc
    rw [mul_sub] at this
    rw [← Ideal.Quotient.eq_zero_iff_mem, map_sub] at this hb ⊢
    convert this using 2
    rw [Int.cast_mul, _root_.map_mul, _root_.map_mul]
    congr 1
    exact (sub_eq_zero.mp hb).symm

example {R A : Type _} [CommRing R] [CommRing A] [Algebra R A] [IsCyclotomicExtension {p} R A]
    [Fact (p : ℕ).Prime] (a : A) :
    ∃ m : R, a ^ (p : ℕ) - algebraMap R A m ∈ span ({(p : A)} : Set A) := by
  by_cases hpunit : ↑(p : ℕ) ∈ nonunits A
  swap
  · simp only [mem_nonunits_iff, Classical.not_not] at hpunit
    exact ⟨0, by simp [Ideal.span_singleton_eq_top.2 hpunit]⟩
  have : a ∈ Algebra.adjoin R _ := @adjoin_roots {p} R A _ _ _ _ a
  refine' Algebra.adjoin_induction this _ (fun r => ⟨r ^ (p : ℕ), by simp⟩) _ _
  · rintro x ⟨hx_w, hx_m, hx_p⟩
    simp only [Set.mem_singleton_iff] at hx_m
    rw [hx_m] at hx_p
    exact ⟨1, by simp [hx_p]⟩
  · rintro x y ⟨b, hb⟩ ⟨c, hc⟩
    use c + b
    rw [← Ideal.Quotient.eq_zero_iff_mem, map_sub, sub_eq_zero] at hb hc ⊢
    haveI : CharP (A ⧸ span ({(p : A)} : Set A)) (p : ℕ) := by
      convert CharP.quotient A (p : ℕ) hpunit
    rw [map_add, map_pow, map_add, add_pow_char_of_commute (A ⧸ span ({(p : A)} : Set A)) _ _
      (Commute.all _ _), ← map_pow, ← map_pow]
    rw [hb, hc]
    simp [add_comm]
  · rintro x y ⟨b, hb⟩ ⟨c, hc⟩
    rw [mul_pow]
    use b * c
    rw [← Ideal.Quotient.eq_zero_iff_mem, map_sub, sub_eq_zero] at hb hc ⊢
    simp only [_root_.map_mul, Quotient.mk_algebraMap, hb, hc]


instance aaaa [Fact (p : ℕ).Prime] : IsCyclotomicExtension {p} ℤ (𝓞 L) :=
  let _ := (zeta_spec p ℚ L).adjoin_isCyclotomicExtension ℤ
  IsCyclotomicExtension.equiv {p} _ _ (zeta_spec p ℚ L).adjoinEquivRingOfIntegers'

local notation "R" => 𝓞 (CyclotomicField p ℚ)

-- TODO I (alex) am not sure whether this is better as ideal span,
-- or fractional_ideal.span_singleton
/-- The principal ideal generated by `x + y ζ^i` for integer `x` and `y` -/
@[nolint unusedArguments]
def fltIdeals [Fact (p : ℕ).Prime] (x y : ℤ) {η : R} (_ : η ∈ nthRootsFinset p R) : Ideal R :=
  Ideal.span ({x + η * y} : Set R)

variable {p}

-- why does this not update (n : ℕ+)?
theorem mem_fltIdeals [Fact (p : ℕ).Prime] (x y : ℤ) {η : R} (hη : η ∈ nthRootsFinset p R) :
    ↑x + η * ↑y ∈ fltIdeals p x y hη :=
  mem_span_singleton.mpr dvd_rfl

theorem Ideal.le_add {S : Type _} [CommRing S] (a b c d : Ideal S) (hab : a ≤ b) (hcd : c ≤ d) :
    a + c ≤ b + d := by
  simp at *
  constructor
  apply le_trans hab (@le_sup_left _ _ _ _)
  apply le_trans hcd (@le_sup_right _ _ _ _)

theorem not_coprime_not_top {S : Type _} [CommRing S] (a b : Ideal S) :
    ¬IsCoprime a b ↔ a + b ≠ ⊤ := by
  apply not_congr
  rw [IsCoprime]
  constructor
  intro h
  obtain ⟨x, y, hxy⟩ := h
  rw [eq_top_iff_one]
  have h2 : x * a + y * b ≤ a + b := by apply Ideal.le_add; all_goals apply mul_le_left
  apply h2
  rw [hxy]
  simp
  intro h
  refine' ⟨1, 1, _⟩
  simp only [one_eq_top, top_mul, Submodule.add_eq_sup, ge_iff_le]
  rw [← h]
  rfl

instance a1 : IsGalois ℚ (CyclotomicField p ℚ) :=
  IsCyclotomicExtension.isGalois p _ _

instance a2 : FiniteDimensional ℚ (CyclotomicField p ℚ) :=
  IsCyclotomicExtension.finiteDimensional {p} _ _

instance a3 : NumberField (CyclotomicField p ℚ) :=
  IsCyclotomicExtension.numberField {p} ℚ _

open IsPrimitiveRoot

attribute [-instance] CharP.CharOne.subsingleton

theorem nth_roots_prim [Fact (p : ℕ).Prime] {η : R} (hη : η ∈ nthRootsFinset p R) (hne1 : η ≠ 1) :
    IsPrimitiveRoot η p := by
  have hζ' := (zeta_spec p ℚ (CyclotomicField p ℚ)).unit'_coe
  rw [← SetLike.mem_coe, nthRoots_one_eq_biUnion_primitiveRoots' hζ', mem_coe,
    @Finset.mem_biUnion _ _ (_) _ _ _] at hη
  obtain ⟨a, ha, h2⟩ := hη
  have ha2 : a = p := by
    rw [Nat.Prime.divisors (Fact.out : Nat.Prime p), mem_insert, mem_singleton] at ha
    cases' ha with ha ha
    exfalso
    rw [ha] at h2
    simp at h2
    rw [h2] at hne1
    exact hne1 rfl
    exact ha
  rw [ha2] at h2
  have hn : 0 < (p : ℕ) := by norm_num
  rw [mem_primitiveRoots hn] at h2
  exact h2

theorem prim_coe (ζ : R) (hζ : IsPrimitiveRoot ζ p) : IsPrimitiveRoot (ζ : CyclotomicField p ℚ) p :=
  coe_submonoidClass_iff.mpr hζ

theorem zeta_sub_one_dvb_p [Fact (p : ℕ).Prime] (ph : 5 ≤ p) {η : R} (hη : η ∈ nthRootsFinset p R)
    (hne1 : η ≠ 1) : 1 - η ∣ (p : R) := by
  have h00 : 1 - η ∣ (p : R) ↔ η - 1 ∣ (p : R) :=
    by
    have hh : -(η - 1) = 1 - η := by ring
    simp_rw [← hh]
    apply neg_dvd
  rw [h00]
  have : IsPrimitiveRoot (η : CyclotomicField p ℚ) p := by
    apply prim_coe η (nth_roots_prim hη hne1)
  have h0 : p ≠ 2 := by
    intro hP
    rw [hP] at ph
    simp at ph
  have h := RingOfIntegers.dvd_norm ℚ (η - 1 : R)
  have h2 := IsPrimitiveRoot.sub_one_norm_prime this (cyclotomic.irreducible_rat p.2) h0
  convert h
  ext
  rw [RingOfIntegers.coe_algebraMap_norm]
  norm_cast at h2
  simp [h2]

theorem one_sub_zeta_prime [Fact (p : ℕ).Prime] (ph : 5 ≤ p) {η : R} (hη : η ∈ nthRootsFinset p R)
    (hne1 : η ≠ 1) : Prime (1 - η) := by
  replace ph : p ≠ 2
  · intro h
    rw [h] at ph
    simp at ph
  have h := prim_coe η (nth_roots_prim hη hne1)
  have := Rat.zeta_sub_one_prime' h ph
  have H :
    (⟨η - 1, Subalgebra.sub_mem _ (h.isIntegral p.pos) (Subalgebra.one_mem _)⟩ : R) = η - 1 := rfl
  rw [H] at this
  simpa using this.neg

theorem diff_of_roots [hp : Fact (p : ℕ).Prime] (ph : 5 ≤ p) {η₁ η₂ : R}
    (hη₁ : η₁ ∈ nthRootsFinset p R) (hη₂ : η₂ ∈ nthRootsFinset p R) (hdiff : η₁ ≠ η₂)
    (hwlog : η₁ ≠ 1) : ∃ u : Rˣ, η₁ - η₂ = u * (1 - η₁) := by
  replace ph : 2 ≤ p := le_trans (by norm_num) ph
  have h := nth_roots_prim hη₁ hwlog
  obtain ⟨i, ⟨H, hi⟩⟩ := h.eq_pow_of_pow_eq_one ((mem_nthRootsFinset hp.out.pos).1 hη₂) hp.out.pos
  have hi1 : 1 ≠ i := by
    intro hi1
    rw [← hi1, pow_one] at hi
    exact hdiff hi
  obtain ⟨u, hu⟩ :=
    CyclotomicUnit.IsPrimitiveRoot.zeta_pow_sub_eq_unit_zeta_sub_one R ph hp.out hp.out.one_lt H
      hi1 h
  refine' ⟨u, _⟩
  rw [← hu, hi, pow_one]

theorem diff_of_roots2 [Fact (p : ℕ).Prime] (ph : 5 ≤ p) {η₁ η₂ : R} (hη₁ : η₁ ∈ nthRootsFinset p R)
    (hη₂ : η₂ ∈ nthRootsFinset p R) (hdiff : η₁ ≠ η₂) (hwlog : η₁ ≠ 1) :
    ∃ u : Rˣ, η₂ - η₁ = u * (1 - η₁) := by
  obtain ⟨u, hu⟩ := diff_of_roots ph hη₁ hη₂ hdiff hwlog
  refine' ⟨-u, _⟩
  rw [Units.val_neg, neg_mul, ← hu]
  ring

instance arg : IsDedekindDomain R :=
  inferInstance

instance : AddCommGroup R := AddCommGroupWithOne.toAddCommGroup
instance : AddCommMonoid R := AddCommGroup.toAddCommMonoid

lemma fltIdeals_coprime2_lemma [Fact (p : ℕ).Prime] (ph : 5 ≤ p) {x y : ℤ} {η₁ η₂ : R}
    (hη₁ : η₁ ∈ nthRootsFinset p R)
    (hη₂ : η₂ ∈ nthRootsFinset p R) (hdiff : η₁ ≠ η₂) (hp : IsCoprime x y)
    (hp2 : ¬(p : ℤ) ∣ (x + y : ℤ)) (hwlog : η₁ ≠ 1) :
    (fltIdeals p x y hη₁) ⊔ (fltIdeals p x y hη₂) = ⊤ := by
  -- Note: `by_contra h` was extremely slow here.
  apply by_contradiction
  intro h
  let I := fltIdeals p x y hη₁ ⊔ fltIdeals p x y hη₂
  obtain ⟨P, hP1, hP2⟩ := exists_le_maximal I h
  have hiP : fltIdeals p x y hη₁ ≤ P := le_trans le_sup_left hP2
  have hel1 : ∃ v : Rˣ, (v : R) * y * (1 - η₁) ∈ I := by
    obtain ⟨v, hv⟩ := diff_of_roots ph hη₁ hη₂ hdiff hwlog
    refine ⟨v, ?_⟩
    have := Ideal.sub_mem _
      (mem_sup_left (mem_fltIdeals x y hη₁)) (mem_sup_right (mem_fltIdeals x y hη₂))
    rwa [add_sub_add_left_eq_sub, ← sub_mul, hv, mul_right_comm] at this
  have hel2 : ∃ v : Rˣ, (v : R) * x * (1 - η₁) ∈ I := by
    obtain ⟨v, hv⟩ := diff_of_roots2 ph hη₁ hη₂ hdiff hwlog
    refine ⟨v, ?_⟩
    have := Ideal.add_mem _ (mul_mem_left _ η₂ (mem_sup_left (mem_fltIdeals x y hη₁)))
        (mul_mem_left _ (-η₁) (mem_sup_right (mem_fltIdeals x y hη₂)))
    have h1 : η₂ * (↑x + η₁ * ↑y) + -η₁ * (↑x + η₂ * ↑y) = (η₂ - η₁) * x := by ring
    rwa [h1, hv, mul_right_comm] at this
  have hel11 : (y : R) * (1 - η₁) ∈ P := by
    obtain ⟨v, hv⟩ := hel1
    rw [mul_assoc] at hv
    have hvunit : IsUnit (v : R) := Units.isUnit v
    apply (unit_mul_mem_iff_mem P hvunit).1 _
    apply hP2
    apply hv
  have hel22 : (x : R) * (1 - η₁) ∈ P := by
    obtain ⟨v, hv⟩ := hel2
    rw [mul_assoc] at hv
    have hvunit : IsUnit (v : R) := Units.isUnit v
    apply (unit_mul_mem_iff_mem P hvunit).1 _
    apply hP2
    apply hv
  have hPrime := hP1.isPrime
  have hprime2 := IsPrime.mem_or_mem hPrime hel11
  have hprime3 := IsPrime.mem_or_mem hPrime hel22
  have HC : 1 - η₁ ∈ P → False := by
    intro h
    have eta_sub_one_ne_zero := sub_ne_zero.mpr (Ne.symm hwlog)
    have hηprime : IsPrime (Ideal.span ({1 - η₁} : Set R)) := by
      rw [span_singleton_prime eta_sub_one_ne_zero]
      apply one_sub_zeta_prime ph hη₁ hwlog
    have H5 : IsPrime (Ideal.span ({(p : ℤ)} : Set ℤ)) := by
      have h2 : (p : ℤ) ≠ 0 := by simp
      have h1 : Prime (p : ℤ) := by
        rw [← prime_iff_prime_int]
        exact Fact.out
      rw [span_singleton_prime h2]
      apply h1
    have hηP : Ideal.span ({1 - η₁} : Set R) = P := by
      have hle : Ideal.span ({1 - η₁} : Set R) ≤ P := by rw [span_le]; simp [h]
      apply (@Ring.DimensionLeOne.prime_le_prime_iff_eq _ _ _ _ _ hηprime hPrime _).1 hle
      intro hbot
      rw [span_eq_bot] at hbot
      simp only [Set.mem_singleton_iff, forall_eq, sub_eq_zero] at hbot
      exact hwlog hbot.symm
    have hcapZ : P.comap (Int.castRingHom R) = Ideal.span ({(p : ℤ)} : Set ℤ) := by
      have H1 : Ideal.span ({(p : ℤ)} : Set ℤ) ≤ P.comap (Int.castRingHom R) := by
        rw [← hηP]
        apply le_comap_of_map_le _
        rw [map_span]
        simp
        rw [span_singleton_le_span_singleton]
        apply zeta_sub_one_dvb_p ph hη₁ hwlog
      have H2 : IsPrime (P.comap (Int.castRingHom R)) := by
        apply @IsPrime.comap _ _ _ _ _ _ _ _ hPrime
      have H4 : Ideal.span ({(p : ℤ)} : Set ℤ) ≠ ⊥ := by simp
      apply ((@Ring.DimensionLeOne.prime_le_prime_iff_eq _ _ _ _ _ H5 H2 H4).1 H1).symm
    have hxyinP : (x + y : R) ∈ P := by
      have H1 : (x : R) + η₁ * y ∈ P := by
        apply hiP
        apply Submodule.mem_span_singleton_self
      have H2 : η₁ * y = y - y * (1 - η₁) := by ring
      rw [H2] at H1
      have H3 : ↑x + (↑y - ↑y * (1 - η₁)) = ↑x + ↑y + -↑y * (1 - η₁) := by ring
      rw [H3] at H1
      have H4 : -↑y * (1 - η₁) ∈ P := by
        rw [← hηP]; rw [Ideal.mem_span_singleton']
        refine' ⟨-(y : R), rfl⟩
      apply (Ideal.add_mem_iff_left P H4).1 H1
    have hxyinP2 : x + y ∈ Ideal.span ({(p : ℤ)} : Set ℤ) := by rw [← hcapZ]; simp [hxyinP]
    rw [mem_span_singleton] at hxyinP2
    apply absurd hxyinP2 hp2
  cases' hprime2 with hprime2 hprime2
  cases' hprime3 with hprime3 hprime3
  obtain ⟨a, b, hab⟩ := hp
  have hone := P.add_mem (Ideal.mul_mem_left P a hprime3) (Ideal.mul_mem_left P b hprime2)
  norm_cast at hone
  rw [hab] at hone
  norm_cast at hone
  rw [← eq_top_iff_one] at hone
  have hcontra := IsPrime.ne_top hPrime
  rw [hone] at hcontra
  simp only [Ne.def, eq_self_iff_true, not_true] at hcontra
  apply HC hprime3
  apply HC hprime2

theorem fltIdeals_coprime2 [Fact (p : ℕ).Prime] (ph : 5 ≤ p) {x y : ℤ} {η₁ η₂ : R}
    (hη₁ : η₁ ∈ nthRootsFinset p R)
    (hη₂ : η₂ ∈ nthRootsFinset p R) (hdiff : η₁ ≠ η₂) (hp : IsCoprime x y)
    (hp2 : ¬(p : ℤ) ∣ (x + y : ℤ)) (hwlog : η₁ ≠ 1) : IsCoprime (fltIdeals p x y hη₁)
    (fltIdeals p x y hη₂) := by
  apply not_not.mp
  rw [not_coprime_not_top, not_not]
  exact fltIdeals_coprime2_lemma ph hη₁ hη₂ hdiff hp hp2 hwlog

theorem aux_lem_flt [Fact (p : ℕ).Prime] {x y z : ℤ} (H : x ^ (p : ℕ) + y ^ (p : ℕ) = z ^ (p : ℕ))
    (caseI : ¬↑p ∣ x * y * z) : ¬(p : ℤ) ∣ (x + y : ℤ) := by
  intro habs
  replace habs : ↑(p : ℕ) ∣ (x + y : ℤ) := by simpa using habs
  rw [← ZMod.int_cast_zmod_eq_zero_iff_dvd, Int.cast_add] at habs
  replace H := congr_arg (fun x : ℤ => (x : ZMod p)) H.symm
  simp only [Int.cast_add, Int.cast_pow, ZMod.pow_card, habs,
    ZMod.int_cast_zmod_eq_zero_iff_dvd] at H
  exact caseI (Dvd.dvd.mul_left H _)

theorem fltIdeals_coprime (hpri : (p : ℕ).Prime) (p5 : 5 ≤ p) {x y z : ℤ}
    (H : x ^ (p : ℕ) + y ^ (p : ℕ) = z ^ (p : ℕ)) {η₁ η₂ : R} (hxy : IsCoprime x y)
    (hη₁ : η₁ ∈ nthRootsFinset p R) (hη₂ : η₂ ∈ nthRootsFinset p R) (hdiff : η₁ ≠ η₂)
    (caseI : ¬↑p ∣ x * y * z) :
    have : Fact (p : ℕ).Prime := ⟨hpri⟩
    IsCoprime (fltIdeals p x y hη₁) (fltIdeals p x y hη₂) := by
  have : Fact (p : ℕ).Prime := ⟨hpri⟩
  by_cases h : η₁ ≠ 1
  apply fltIdeals_coprime2 p5 hη₁ hη₂ hdiff hxy (aux_lem_flt H caseI) h
  have h2 : η₂ ≠ 1 := by
    simp at h
    rw [h] at hdiff
    exact hdiff.symm
  have := fltIdeals_coprime2 p5 hη₂ hη₁ hdiff.symm hxy (aux_lem_flt H caseI) h2
  apply IsCoprime.symm
  exact this

variable {L}

theorem dvd_last_coeff_cycl_integer [hp : Fact (p : ℕ).Prime] {ζ : 𝓞 L}
    (hζ : IsPrimitiveRoot ζ p) {f : Fin p → ℤ}
    (hf : ∃ i, f i = 0) {m : ℤ} (hdiv : ↑m ∣ ∑ j, f j • ζ ^ (j : ℕ)) :
    m ∣ f ⟨(p : ℕ).pred, pred_lt hp.out.ne_zero⟩ := by
  obtain ⟨i, Hi⟩ := hf
  have hlast :
    (Fin.castIso (succ_pred_prime hp.out)) (Fin.last (p : ℕ).pred) =
    ⟨(p : ℕ).pred, pred_lt hp.out.ne_zero⟩ := Fin.ext rfl
  have h : ∀ x, (Fin.castIso (succ_pred_prime hp.out)) (Fin.castSuccEmb x) =
    ⟨x, lt_trans x.2 (pred_lt hp.out.ne_zero)⟩ := fun x => Fin.ext rfl
  let ζ' := (ζ : L)
  have hζ' : IsPrimitiveRoot ζ' p := IsPrimitiveRoot.coe_submonoidClass_iff.2 hζ
  have hcoe : ζ = ⟨ζ', hζ'.isIntegral p.pos⟩ := by simp
  set b := hζ'.integralPowerBasis' with hb
  have hdim : b.dim = (p : ℕ).pred := by rw [hζ'.power_basis_int'_dim, totient_prime hp.out,
    pred_eq_sub_one]
  by_cases H : i = ⟨(p : ℕ).pred, pred_lt hp.out.ne_zero⟩
  · simp [H.symm, Hi]
  have hi : ↑i < (p : ℕ).pred := by
    by_contra' habs
    simp [le_antisymm habs (le_pred_of_lt (Fin.is_lt i))] at H
  obtain ⟨y, hy⟩ := hdiv
  rw [← Equiv.sum_comp (Fin.castIso (succ_pred_prime hp.out)).toEquiv, Fin.sum_univ_castSucc] at hy
  simp only [hlast, h, RelIso.coe_fn_toEquiv, Fin.val_mk] at hy
  rw [hζ.pow_sub_one_eq hp.out.one_lt, ← sum_neg_distrib, smul_sum, sum_range, ← sum_add_distrib,
    ← (Fin.castIso hdim).toEquiv.sum_comp] at hy
  simp only [RelIso.coe_fn_toEquiv, Fin.coe_cast, mul_neg, ← Subtype.coe_inj, Fin.coe_castSucc,
    Fin.coe_orderIso_apply] at hy
  push_cast at hy
  conv_lhs at hy =>
    congr; rfl; ext x
    rw [smul_neg]
    congr; congr; rfl; congr
    rw [hcoe, ← hζ'.integralPowerBasis'_gen, ← hb]
    rfl; rfl; congr; congr; rfl; congr
    rw [hcoe, ← hζ'.integralPowerBasis'_gen, ← hb]
  conv_lhs at hy =>
    congr; rfl; ext x
    rw [← SubsemiringClass.coe_pow, ← show ∀ y, _ = _ from fun y => congr_fun b.coe_basis y,
      ← sub_eq_add_neg]
  norm_cast at hy
  rw [sum_sub_distrib] at hy
  replace hy := congr_arg (b.basis.coord ((Fin.castIso hdim.symm) ⟨i, hi⟩)) hy
  rw [← b.basis.equivFun_symm_apply, ← b.basis.equivFun_symm_apply, LinearMap.map_sub,
    b.basis.coord_equivFun_symm, b.basis.coord_equivFun_symm, ← smul_eq_mul,
    ← zsmul_eq_smul_cast] at hy
  obtain ⟨n, hn⟩ := b.basis.dvd_coord_smul ((Fin.castIso hdim.symm) ⟨i, hi⟩) y m
  rw [hn] at hy
  simp only [Fin.castIso_apply, Fin.cast_mk, Fin.castSucc_mk, Fin.eta, Hi, zero_sub,
    neg_eq_iff_eq_neg] at hy
  simp [hy, dvd_neg]

theorem dvd_coeff_cycl_integer (hp : (p : ℕ).Prime) {ζ : 𝓞 L} (hζ : IsPrimitiveRoot ζ p)
    {f : Fin p → ℤ} (hf : ∃ i, f i = 0) {m : ℤ} (hdiv : ↑m ∣ ∑ j, f j • ζ ^ (j : ℕ)) :
    ∀ j, m ∣ f j := by
  let ζ' := (ζ : L)
  have : Fact (p : ℕ).Prime := ⟨hp⟩
  have hζ' : IsPrimitiveRoot ζ' p := IsPrimitiveRoot.coe_submonoidClass_iff.2 hζ
  have hcoe : ζ = ⟨ζ', hζ'.isIntegral p.pos⟩ := by simp
  have hlast : (Fin.castIso (succ_pred_prime hp)) (Fin.last (p : ℕ).pred) =
      ⟨(p : ℕ).pred, pred_lt hp.ne_zero⟩ := Fin.ext rfl
  have h : ∀ x, (Fin.castIso (succ_pred_prime hp)) (Fin.castSuccEmb x) =
    ⟨x, lt_trans x.2 (pred_lt hp.ne_zero)⟩ := fun x => Fin.ext rfl
  set b := hζ'.integralPowerBasis' with hb
  have hdim : b.dim = (p : ℕ).pred := by rw [hζ'.power_basis_int'_dim, totient_prime hp,
    pred_eq_sub_one]
  have last_dvd := dvd_last_coeff_cycl_integer hζ hf hdiv
  intro j
  by_cases H : j = ⟨(p : ℕ).pred, pred_lt hp.ne_zero⟩
  · simpa [H] using last_dvd
  have hj : ↑j < (p : ℕ).pred := by
    by_contra' habs
    simp [le_antisymm habs (le_pred_of_lt (Fin.is_lt j))] at H
  obtain ⟨y, hy⟩ := hdiv
  rw [← Equiv.sum_comp (Fin.castIso (succ_pred_prime hp)).toEquiv, Fin.sum_univ_castSucc] at hy
  simp only [hlast, h, RelIso.coe_fn_toEquiv, Fin.val_mk] at hy
  rw [hζ.pow_sub_one_eq hp.one_lt, ← sum_neg_distrib, smul_sum, sum_range, ← sum_add_distrib,
    ← (Fin.castIso hdim).toEquiv.sum_comp] at hy
  simp only [RelIso.coe_fn_toEquiv, Fin.coe_cast, mul_neg, ← Subtype.coe_inj, Fin.coe_castSucc,
    Fin.coe_orderIso_apply] at hy
  push_cast at hy
  conv_lhs at hy =>
    congr; rfl; ext x
    rw [smul_neg]
    congr; congr; rfl; congr
    rw [hcoe, ← hζ'.integralPowerBasis'_gen, ← hb]
    rfl; rfl; congr; congr; rfl; congr
    rw [hcoe, ← hζ'.integralPowerBasis'_gen, ← hb]
  conv_lhs at hy =>
    congr; rfl; ext x
    rw [← SubsemiringClass.coe_pow, ← show ∀ y, _ = _ from fun y => congr_fun b.coe_basis y,
      ← sub_eq_add_neg]
  norm_cast at hy
  rw [sum_sub_distrib] at hy
  replace hy := congr_arg (b.basis.coord ((Fin.castIso hdim.symm) ⟨j, hj⟩)) hy
  rw [← b.basis.equivFun_symm_apply, ← b.basis.equivFun_symm_apply, LinearMap.map_sub,
    b.basis.coord_equivFun_symm, b.basis.coord_equivFun_symm] at hy
  simp only [Fin.castIso_apply, Fin.cast_mk, Fin.castSucc_mk, Fin.eta, Basis.coord_apply,
    sub_eq_iff_eq_add] at hy
  obtain ⟨n, hn⟩ := b.basis.dvd_coord_smul ((Fin.cast hdim.symm) ⟨j, hj⟩) y m
  rw [hy, ← smul_eq_mul, ← zsmul_eq_smul_cast, ← b.basis.coord_apply, ← Fin.cast_mk, hn]
  exact dvd_add (dvd_mul_right _ _) last_dvd
