import BealRegular.CubicIdealCertificate

#print axioms BealRegular.CubicIdealCertificate.span_pair_cube_eq_span_singleton_of_certificate
#print axioms BealRegular.CubicIdealCertificate.span_pair_cube_isPrincipal_of_certificate
#print axioms BealRegular.CubicIdealCertificate.span_pair_cube_eq_span_singleton_of_aeval_certificate
#print axioms BealRegular.CubicIdealCertificate.kummerDedekindIdeal_cube_eq_span_singleton_of_polynomial_certificate
#print axioms BealRegular.CubicIdealCertificate.kummerDedekindIdeal_cube_isPrincipal_of_polynomial_certificate
