module

public import Mathlib.Algebra.Polynomial.AlgebraMap
public import Mathlib.RingTheory.Ideal.Operations

/-!
# Kernel verifier for cubic ideal certificates

This file isolates the algebra needed to check certificates of the form

```text
(a, b)^3 = (g).
```

Four divisibility identities put the four degree-three monomials in `(g)`;
a fifth linear-combination identity puts `g` back in `(a, b)^3`.  The
polynomial theorem below transports exactly those five identities through
`aeval`, with a supplied relation polynomial that vanishes at the evaluation
point.  No primality, number-field, or computer-algebra assertion is needed by
the verifier itself.
-/

@[expose] public section

open Ideal Polynomial

namespace BealRegular.CubicIdealCertificate

/-- A five-identity certificate proving that the cube of a two-generated ideal
is generated by `g`.

The first four equations are the divisibility witnesses for `a^3`, `a^2 b`,
`a b^2`, and `b^3`.  The final equation is the reverse-containment witness. -/
theorem span_pair_cube_eq_span_singleton_of_certificate
    {R : Type*} [CommRing R]
    {a b g q0 q1 q2 q3 c0 c1 c2 c3 : R}
    (h0 : a ^ 3 = g * q0)
    (h1 : a ^ 2 * b = g * q1)
    (h2 : a * b ^ 2 = g * q2)
    (h3 : b ^ 3 = g * q3)
    (h4 : g = c0 * a ^ 3 + c1 * (a ^ 2 * b) +
      c2 * (a * b ^ 2) + c3 * b ^ 3) :
    (span {a, b} : Ideal R) ^ 3 = span {g} := by
  let A : Ideal R := span {a}
  let B : Ideal R := span {b}
  let J : Ideal R := span {g}
  have h0le : span {(a * a) * a} ≤ J :=
    Ideal.span_singleton_le_span_singleton.mpr
      ⟨q0, by
        calc
          (a * a) * a = a * (a * a) := by ac_rfl
          _ = g * q0 := by simpa only [pow_three] using h0⟩
  have h1le : span {(a * a) * b} ≤ J :=
    Ideal.span_singleton_le_span_singleton.mpr
      ⟨q1, by simpa only [pow_two] using h1⟩
  have h2le : span {(a * b) * b} ≤ J :=
    Ideal.span_singleton_le_span_singleton.mpr
      ⟨q2, by simpa only [pow_two, mul_assoc] using h2⟩
  have h3le : span {(b * b) * b} ≤ J :=
    Ideal.span_singleton_le_span_singleton.mpr
      ⟨q3, by
        calc
          (b * b) * b = b * (b * b) := by ac_rfl
          _ = g * q3 := by simpa only [pow_three] using h3⟩
  have h1le' : span {(b * a) * a} ≤ J := by
    rwa [show (b * a) * a = (a * a) * b by ac_rfl]
  have h2le' : span {(b * b) * a} ≤ J := by
    rwa [show (b * b) * a = (a * b) * b by ac_rfl]
  have h2le'' : span {(b * a) * b} ≤ J := by
    rwa [show (b * a) * b = (a * b) * b by ac_rfl]
  apply le_antisymm
  · rw [show (span {a, b} : Ideal R) = A ⊔ B by simp [A, B, Ideal.span_insert],
      pow_succ, pow_two]
    simp only [Ideal.sup_mul, Ideal.mul_sup]
    refine sup_le
      (sup_le (sup_le ?_ ?_) (sup_le ?_ ?_))
      (sup_le (sup_le ?_ ?_) (sup_le ?_ ?_))
    · simpa only [A, Ideal.span_singleton_mul_span_singleton] using h0le
    · simpa only [A, B, Ideal.span_singleton_mul_span_singleton] using h1le'
    · simpa only [A, B, Ideal.span_singleton_mul_span_singleton, mul_assoc, mul_comm,
        mul_left_comm] using h1le
    · simpa only [A, B, Ideal.span_singleton_mul_span_singleton] using h2le'
    · simpa only [A, B, Ideal.span_singleton_mul_span_singleton, mul_assoc, mul_comm,
        mul_left_comm] using h1le
    · simpa only [A, B, Ideal.span_singleton_mul_span_singleton] using h2le''
    · simpa only [A, B, Ideal.span_singleton_mul_span_singleton, mul_assoc, mul_comm,
        mul_left_comm] using h2le
    · simpa only [B, Ideal.span_singleton_mul_span_singleton] using h3le
  · rw [Ideal.span_le, Set.singleton_subset_iff]
    let I : Ideal R := span {a, b}
    have ha : a ∈ I := Ideal.subset_span (by simp)
    have hb : b ∈ I := Ideal.subset_span (by simp)
    have ha3 : a ^ 3 ∈ I ^ 3 := Ideal.pow_mem_pow ha 3
    have ha2b : a ^ 2 * b ∈ I ^ 3 := by
      have hm := Ideal.mul_mem_mul ha (Ideal.mul_mem_mul ha hb)
      rw [pow_three]
      simpa only [pow_two, mul_assoc] using hm
    have hab2 : a * b ^ 2 ∈ I ^ 3 := by
      have hm := Ideal.mul_mem_mul ha (Ideal.mul_mem_mul hb hb)
      rw [pow_three]
      simpa only [pow_two, mul_assoc] using hm
    have hb3 : b ^ 3 ∈ I ^ 3 := Ideal.pow_mem_pow hb 3
    rw [h4]
    exact (I ^ 3).add_mem
      ((I ^ 3).add_mem
        ((I ^ 3).add_mem ((I ^ 3).mul_mem_left c0 ha3)
          ((I ^ 3).mul_mem_left c1 ha2b))
        ((I ^ 3).mul_mem_left c2 hab2))
      ((I ^ 3).mul_mem_left c3 hb3)

/-- The equality certificate immediately supplies the `IsPrincipal` witness
expected by class-group exponent arguments. -/
theorem span_pair_cube_isPrincipal_of_certificate
    {R : Type*} [CommRing R]
    {a b g q0 q1 q2 q3 c0 c1 c2 c3 : R}
    (h0 : a ^ 3 = g * q0)
    (h1 : a ^ 2 * b = g * q1)
    (h2 : a * b ^ 2 = g * q2)
    (h3 : b ^ 3 = g * q3)
    (h4 : g = c0 * a ^ 3 + c1 * (a ^ 2 * b) +
      c2 * (a * b ^ 2) + c3 * b ^ 3) :
    Submodule.IsPrincipal ((span {a, b} : Ideal R) ^ 3) :=
  ⟨g, span_pair_cube_eq_span_singleton_of_certificate h0 h1 h2 h3 h4⟩

/-- Evaluate the five polynomial identities modulo a supplied relation
`Phi(θ) = 0`, then invoke the ring-level cubic-ideal verifier. -/
theorem span_pair_cube_eq_span_singleton_of_aeval_certificate
    {S R : Type*} [CommRing S] [CommRing R] [Algebra S R]
    (θ : R)
    {A B G Phi Q0 Q1 Q2 Q3 R0 R1 R2 R3 R4 C0 C1 C2 C3 : S[X]}
    (hPhi : aeval θ Phi = 0)
    (h0 : A ^ 3 = G * Q0 + Phi * R0)
    (h1 : A ^ 2 * B = G * Q1 + Phi * R1)
    (h2 : A * B ^ 2 = G * Q2 + Phi * R2)
    (h3 : B ^ 3 = G * Q3 + Phi * R3)
    (h4 : G = C0 * A ^ 3 + C1 * (A ^ 2 * B) +
      C2 * (A * B ^ 2) + C3 * B ^ 3 + Phi * R4) :
    (span {aeval θ A, aeval θ B} : Ideal R) ^ 3 = span {aeval θ G} := by
  apply span_pair_cube_eq_span_singleton_of_certificate
      (q0 := aeval θ Q0) (q1 := aeval θ Q1)
      (q2 := aeval θ Q2) (q3 := aeval θ Q3)
      (c0 := aeval θ C0) (c1 := aeval θ C1)
      (c2 := aeval θ C2) (c3 := aeval θ C3)
  · simpa only [map_pow, map_add, map_mul, hPhi, zero_mul, add_zero] using
      congrArg (aeval θ) h0
  · simpa only [map_pow, map_add, map_mul, hPhi, zero_mul, add_zero] using
      congrArg (aeval θ) h1
  · simpa only [map_pow, map_add, map_mul, hPhi, zero_mul, add_zero] using
      congrArg (aeval θ) h2
  · simpa only [map_pow, map_add, map_mul, hPhi, zero_mul, add_zero] using
      congrArg (aeval θ) h3
  · simpa only [map_pow, map_add, map_mul, hPhi, zero_mul, add_zero] using
      congrArg (aeval θ) h4

/-- The Kummer--Dedekind specialization: the first ideal generator is the
scalar `q`, represented in the certificate by the constant polynomial
`Polynomial.C q`. -/
theorem kummerDedekindIdeal_cube_eq_span_singleton_of_polynomial_certificate
    {S R : Type*} [CommRing S] [CommRing R] [Algebra S R]
    (θ : R) (q : S)
    {F G Phi Q0 Q1 Q2 Q3 R0 R1 R2 R3 R4 C0 C1 C2 C3 : S[X]}
    (hPhi : aeval θ Phi = 0)
    (h0 : (C q) ^ 3 = G * Q0 + Phi * R0)
    (h1 : (C q) ^ 2 * F = G * Q1 + Phi * R1)
    (h2 : (C q) * F ^ 2 = G * Q2 + Phi * R2)
    (h3 : F ^ 3 = G * Q3 + Phi * R3)
    (h4 : G = C0 * (C q) ^ 3 + C1 * ((C q) ^ 2 * F) +
      C2 * ((C q) * F ^ 2) + C3 * F ^ 3 + Phi * R4) :
    (span {algebraMap S R q, aeval θ F} : Ideal R) ^ 3 = span {aeval θ G} := by
  simpa only [aeval_C] using
    span_pair_cube_eq_span_singleton_of_aeval_certificate θ hPhi h0 h1 h2 h3 h4

/-- Principal-ideal endpoint for the Kummer--Dedekind polynomial
certificate. -/
theorem kummerDedekindIdeal_cube_isPrincipal_of_polynomial_certificate
    {S R : Type*} [CommRing S] [CommRing R] [Algebra S R]
    (θ : R) (q : S)
    {F G Phi Q0 Q1 Q2 Q3 R0 R1 R2 R3 R4 C0 C1 C2 C3 : S[X]}
    (hPhi : aeval θ Phi = 0)
    (h0 : (C q) ^ 3 = G * Q0 + Phi * R0)
    (h1 : (C q) ^ 2 * F = G * Q1 + Phi * R1)
    (h2 : (C q) * F ^ 2 = G * Q2 + Phi * R2)
    (h3 : F ^ 3 = G * Q3 + Phi * R3)
    (h4 : G = C0 * (C q) ^ 3 + C1 * ((C q) ^ 2 * F) +
      C2 * ((C q) * F ^ 2) + C3 * F ^ 3 + Phi * R4) :
    Submodule.IsPrincipal
      ((span {algebraMap S R q, aeval θ F} : Ideal R) ^ 3) :=
  ⟨aeval θ G,
    kummerDedekindIdeal_cube_eq_span_singleton_of_polynomial_certificate
      θ q hPhi h0 h1 h2 h3 h4⟩

end BealRegular.CubicIdealCertificate
