import BealRegular.TwentyThreeDesign

#print axioms BealRegular.TwentyThreeDesign.prime_coprime_card_of_forall_pow_eq_one
#print axioms BealRegular.TwentyThreeDesign.isRegularPrime_twentyThree_of_cube
#print axioms BealRegular.TwentyThreeDesign.isRegularPrime_twentyThree_of_exponent_dvd_three
#print axioms BealRegular.TwentyThreeDesign.isRegularPrime_twentyThree_of_card_eq_three
#print axioms BealRegular.TwentyThreeDesign.isRegularPrime_twentyThree_of_minkowski_prime_cubes
#print axioms BealRegular.TwentyThreeDesign.isRegularPrime_twentyThree_of_one_prime_above_cubes
#print axioms BealRegular.TwentyThreeDesign.fermatLastTheoremTwentyThree_of_cube
