import BealRegular.TwentyThreePrimeThreeCube

#print axioms BealRegular.TwentyThreePrimeThreeCube.polynomial_certificate
#print axioms BealRegular.TwentyThreePrimeThreeCube.F_mul_Fbar_add_three_mul_A
#print axioms BealRegular.TwentyThreePrimeThreeCube.F_dvd_cyclotomic_mod_three
#print axioms BealRegular.TwentyThreePrimeThreeCube.order_three_mod_twentyThree
#print axioms BealRegular.TwentyThreePrimeThreeCube.map_F_irreducible
#print axioms BealRegular.TwentyThreePrimeThreeCube.map_F_mem_monicFactorsMod
#print axioms BealRegular.TwentyThreePrimeThreeCube.primeIdealThree_mem_primesOver
#print axioms BealRegular.TwentyThreePrimeThreeCube.primeIdealThree_eq_span
#print axioms BealRegular.TwentyThreePrimeThreeCube.primeIdealThree_inertiaDeg
#print axioms BealRegular.TwentyThreePrimeThreeCube.primeIdealThree_cube_eq_span_generator
#print axioms BealRegular.TwentyThreePrimeThreeCube.primeIdealThree_cube_isPrincipal
#print axioms BealRegular.TwentyThreePrimeThreeCube.exists_prime_above_three_cube_isPrincipal
