import number_theory.cyclotomic.galois_action_on_cyclo

universes u

open finite_dimensional

variables (n : ℕ+) (L : Type u) [field L] [char_zero L]

namespace is_cyclotomic_extension

namespace rat

namespace singleton

variables [is_cyclotomic_extension {n} ℚ L]

lemma finrank : finrank ℚ L = (n : ℕ).totient := sorry

end singleton

end rat

namespace int

namespace singleton

instance : is_integral_closure (cyclotomic_ring n ℤ ℚ) ℤ (cyclotomic_field n ℚ) := sorry

end singleton

end int

end is_cyclotomic_extension

section int_facts

noncomputable theory

local notation `KK` := cyclotomic_field n ℚ

local notation `RR` := number_field.ring_of_integers (cyclotomic_field n ℚ)

--A.K.A theorem:FLT_facts 3
lemma flt_fact_3 [fact (n : ℕ).prime] (a : RR) :
  ∃ (m : ℤ), (a ^ (n : ℕ) - m) ∈ ideal.span ({n} : set RR) := sorry

/-- The principal ideal generated by `x + y ζ^i` for integer `x` and `y` -/
def flt_ideals (x y : ℤ) (i  : ℕ) : ideal RR :=
  ideal.span ({ x+y*(cyclotomic_ring.zeta n ℚ)^i} : set RR)

lemma flt_fact_2 [fact (n : ℕ).prime] (ph: 5 ≤ n) (x y : ℤ) (i j : ℕ) (h : i ≠ j)
  (hp : is_coprime x y) : (flt_ideals n x y i) + (flt_ideals n x y i) = ⊤ := sorry

end int_facts
